# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'SnapEngage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SnapEngage

#remove this after publishing the podspec:
 pod 'SnapEngageSDK', :path =>  "../"

#use this after publishing the podspec: 
#pod 'SnapEngageSDK', :git =>  'https://github.com/SnapEngage/mobilesdk-ios.git'

  target 'SnapEngageTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
